### DISCUSSION TITLE
MacOS X Actions

### DISCUSSION THREAD

**Discussion by steveicarus** [steveicarus/iverilog#447] [Ideas]
Does github actions have MacOS instances that we can use to regression test the MacOS build? I think if we can include Linux, Windows(msys) and macos, then that pretty much covers all the targets we are really willing to support.

**Comment by umarcor** [comment]
Yes, it does: https://github.com/actions/virtual-environments/#available-environments. Adding the following to the workflow file would be the starting point:

```yml
  macos:
    runs-on: macos-latest
    name: '🍎 macOS'
    steps:
    - uses: actions/checkout@v2
...
```
